---

- name: get runner name
  set_fact:
    ins_runner_name: "{{ vars['platform']['repo'][ins_type]['runner']['name'] }}"
  when: ins_runner_name is not defined

- name: get runner version
  set_fact:
    ins_runner_version: "{{ vars['platform']['repo'][ins_type]['runner']['version'] }}"
  when: ins_runner_version is not defined

- name: get delete command
  set_fact:
    ins_delete_command: "{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['delete'] }}"

- name: delete instances
  command: "docker run --rm -v /tmp:/data/repo kloiadocker/klopac-{{ ins_runner_name }}-runner:{{ ins_runner_version }} /bin/bash -c \"cd {{ ins_repo_path }}; {{ ins_delete_command }}\""
  become: true
  register: ins_delete_log

- debug:
    msg: "{{ vars['ins_delete_log'] }}"
  when: vars['platform']['log']['level']=='debug'