---
- name: get worker ips
  shell: "{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['output']['worker']['ips'] }}"
  args:
    chdir:  "{{ ins_repo_path }}"
  register: worker_ips
  when: ins.operation.type != 'delete'

- name: clear worker ips
  shell: "yq -i -y 'del(.ins.worker.net.ip.pool)' /data/vars/instance.yaml"

- name: set worker ips
  shell: "yq -i -y '.ins.worker.net.ip.pool += [\"{{ item }}\"]' /data/vars/instance.yaml"
  loop: '{{ worker_ips.stdout | from_json | list }}'
  when: ins.operation.type != 'delete'

- name: get master ips
  shell: "{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['output']['master']['ips'] }}"
  args:
    chdir:  "{{ ins_repo_path }}"
  register: master_ips
  when: ins.operation.type != 'delete'

- name: clear master ips
  shell: "yq -i -y 'del(.ins.master.net.ip.pool)' /data/vars/instance.yaml"

- name: set master ips
  shell: "yq -i -y '.ins.master.net.ip.pool += [\"{{ item }}\"]' /data/vars/instance.yaml"
  loop: '{{ master_ips.stdout | from_json | list }}'
  when: ins.operation.type != 'delete'

- name: clear public lb dns name
  shell: "yq -i -y 'del(.ins.lb.pub.dnsName)' /data/vars/instance.yaml"

- name: ins get public lb dns name
  shell: "{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['output']['lb']['public']['dnsName'] }}"
  args:
    chdir:  "{{ ins_repo_path }}"
  register: public_lb_dns
  when: ins.operation.type != 'delete'

- name: ins set public lb dns name
  shell: "yq -i -y '.ins.lb.pub.dnsName = [\"{{ public_lb_dns.stdout | from_json }}\"]' /data/vars/instance.yaml"

- name: clear priv lb dns name
  shell: "yq -i -y 'del(.ins.lb.priv.dnsName)' /data/vars/instance.yaml"

- name: ins get private lb dns name
  shell: "{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['output']['lb']['private']['dnsName'] }}"
  args:
    chdir:  "{{ ins_repo_path }}"
  register: private_lb_dns
  when: ins.operation.type != 'delete'

- name: ins set private lb dns name
  shell: "yq -i -y '.ins.lb.priv.dnsName = [\"{{ private_lb_dns.stdout | from_json }}\"]' /data/vars/instance.yaml"
  when: ins.operation.type != 'delete'

- name: get pem path
  set_fact:
    ins_pem_path: "{{ ins_repo_path }}/{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['output']['pem']['path'] }}"

- name: copy pem file
  copy:
    content: "{{ ins_pem_path }}"
    dest: "/data/sensitive/{{ vars['platform']['name'] }}-{{ vars['platform']['environment'] }}-key.pem"
  when: ins.operation.type != 'delete'