---

- name: get runner name
  set_fact:
    ins_runner_name: "{{ vars['platform']['repo'][ins_type]['runner']['name'] }}"
  when: ins_runner_name is not defined

- name: get runner version
  set_fact:
    ins_runner_version: "{{ vars['platform']['repo'][ins_type]['runner']['version'] }}"
  when: ins_runner_version is not defined

- name: get update command
  set_fact:
    ins_update_command: "{{ vars['platform']['repo'][ins_type][provider_name]['dialect']['command']['update'] }}"

- name: update instances
  command: "docker run --rm -v /tmp:/data/repo -e AWS_ACCESS_KEY_ID={{ ins_auth_id }} -e AWS_SECRET_ACCESS_KEY={{ ins_auth_key }} kloiadocker/klopac-{{ ins_runner_name }}-runner:{{ ins_runner_version }} /bin/bash -c \"cd {{ ins_repo_path }}; {{ ins_update_command }}\""
  become: true
  register: ins_update_log
  when: vars['platform']['provider']['name'] == 'aws'

- debug:
    msg: "{{ vars['ins_update_log'] }}"
  when: vars['platform']['log']['level']=='debug'