---

- name: "[FINALIZE] - Create Bundle Directory"
  file:
    state: directory
    owner: 1000
    group: 1000
    mode: 0750
    path: "/data/bundle"
    
- name: "[FINALIZE] - Include Test Output Variables"
  include_vars: /data/bundle/output.yaml
  ignore_errors: true

- name: "[FINALIZE] - Create Pac Output as Markdown"
  template:
    src: templates/output.md.j2
    dest: "/data/bundle/output.md"
    mode: u+rw,g-wx,o-rwx

- name: "[FINALIZE] - Compress Bundle"
  block:
  - name: "[FINALIZE] - Run Subtasks for Instance Output Files"
    include: instance-subtasks.yml filename="{{ vars['ins']['type'] }}"
    when: 
    - vars['ins']['enabled'] | bool
    - vars['ins']['runner']['type'] == "repo" 

  - name: "[FINALIZE] - Run Subtasks for Engine Output Files"
    include: engine-subtasks.yml filename="{{ vars['engine']['type'] }}"
    when: 
    - vars['engine']['enabled'] | bool
    - vars['engine']['runner']['type'] == "repo" 
  
  - name: "[FINALIZE] - Tar Bundle"
    changed_when: false
    command: tar czf /data/bundle.tar.gz .
    args:
      chdir: /data/bundle
 
  when: COMPRESS_BUNDLE | bool
