---

- name: Create bundle directory
  file:
    state: directory
    owner: 1000
    group: 1000
    mode: 0750
    path: "/data/bundle"
    
- name: Include Image Variables
  include_vars: /data/bundle/output.yaml

- name: Create Pac Output
  template:
    src: templates/output.md.j2
    dest: "/data/bundle/output.md"
    mode: u+rw,g-wx,o-rwx

#APPLICATIONS
# - name: Include Applications Variables
#   include_vars: ../vars/applications.yaml

# - name: Run Subtasks for Applications
#   include: app-subtasks.yml filename={{ item }}
#   when: 
#   - "{{ vars['app'][item]['enabled'] | bool }}"
#   - vars['app'][item]['runner']['type'] == "repo" 
#   with_items: "{{ app }}"

#IMAGE
# - name: Include Image Variables
#   include_vars: ../vars/image.yaml

# - name: Run Subtasks for Image
#   include: image-subtasks.yml filename="{{ vars['img']['type'] }}"
#   when: 
#   - "{{ vars['img']['enabled'] | bool }}"
#   - vars['img']['runner']['type'] == "repo" 

- name: Compress Bundle
  block:
  #INSTANCE
  - name: Include Instance Variables
    include_vars: /data/vars/instance.yaml

  - name: Run Subtasks for Instance
    include: instance-subtasks.yml filename="{{ vars['ins']['type'] }}"
    when: 
    - "{{ vars['ins']['enabled'] | bool }}"
    - vars['ins']['runner']['type'] == "repo" 

  #ENGINE
  - name: Include Engine Variables
    include_vars: /data/vars/engine.yaml

  - name: Run Subtasks for Engine
    include: engine-subtasks.yml filename="{{ vars['engine']['type'] }}"
    when: 
    - "{{ vars['engine']['enabled'] | bool }}"
    - vars['engine']['runner']['type'] == "repo" 

  - name: Create bundle from state and config files
    changed_when: false
    command: tar czf /data/bundle.tar.gz .
    args:
      chdir: /data/bundle

  when: COMPRESS_BUNDLE | bool

#INTEGRATIONS
# - name: Include Applications Variables
#   include_vars: ../vars/integrations.yaml

# - name: Run Subtasks for Integrations
#   include: integration-subtasks.yml filename={{ item }}
#   when: 
#   - "{{ vars['int'][item]['enabled'] | bool }}"
#   - vars['int'][item]['runner']['type'] == "repo" 
#   with_items: "{{ int }}"


