---

- name: "[FINALIZE] - Create Bundle Directory"
  become: true
  file:
    state: directory
    owner: 1000
    group: 1000
    mode: 0750
    path: "/data/bundle"
  
- name: "[FINALIZE] - Check that the output.yaml exists"
  stat:
    path: "/data/bundle/output.yaml"
  register: stat_result

- block:
  - name: "[FINALIZE] - Include Test Output Variables"
    include_vars: /data/bundle/output.yaml
  - name: "[FINALIZE] - Create Pac Output as Markdown"
    template:
      src: templates/output.md.j2
      dest: "/data/bundle/output.md"
      mode: u+rw,g-wx,o-rwx
  when: stat_result.stat.exists

- name: "[FINALIZE] - Compress Bundle"
  block:
  - name: "[FINALIZE] - Run Subtasks for Instance Output Files"
    include: instance-subtasks.yml filename="{{ vars['ins']['type'] }}"
    when: 
    - vars['ins']['enabled'] == true

  - name: "[FINALIZE] - Run Subtasks for Engine Output Files"
    include: engine-subtasks.yml filename="{{ vars['engine']['type'] }}"
    when: 
    - vars['engine']['enabled'] == true
  
  - name: "[FINALIZE] - Tar Bundle"
    #changed_when: false
    shell: tar czf /tmp/bundle.tar.gz /data/bundle /data/vars /data/manifests /data/sensitive ; mv /tmp/bundle.tar.gz /data/bundle/bundle.tar.gz
  when: COMPRESS_BUNDLE | bool == true
