---
- name: update "{{ item }}" helm chart
  include_tasks: ../roles/app/tasks/update_obj.yml
  with_items: "{{ app_obj }}"
  register: helm_update_log
  loop_control:
    loop_var: app_exe_obj
  when:
    - vars['app'][app_exe_obj]['runner']['type'] == 'executor'
    - vars['app'][app_exe_obj]['operation']['type'] == 'update'
    - vars['platform']['executor'][app_exe_obj]['helm'] is defined
    - vars['app'][app_exe_obj]['enabled'] == true

- debug:
    msg: "{{ helm_update_log }}"
  when: vars['platform']['log']['level']=='debug'