---
- name: "get runner type {{ app_exe_obj }}"
  set_fact:
    app_runner_type: "{{ vars['app'][app_exe_obj]['runner']['type'] }}"

- name: get runner name "{{ app_exe_obj }}"
  set_fact:
    app_runner_name: "{{ vars['platform'][app_runner_type][app_exe_obj]['runner']['name'] }}"

- name: get runner version "{{ app_exe_obj }}"
  set_fact:
    app_runner_version: "{{ vars['platform'][app_runner_type][app_exe_obj]['runner']['version'] }}"

- name: get "{{ app_exe_obj }}" version
  set_fact:
    app_obj_version: "{{ vars['platform'][app_runner_type][app_exe_obj]['version'] }}"

- name: get runner manifest "{{ app_exe_obj }}"
  set_fact:
    app_helm_manifest_uri: "{{ vars['platform'][app_runner_type][app_exe_obj]['manifest']['uri'] }}"

- name: get runner command for helm "{{ app_exe_obj }}"
  set_fact:
    app_runner_helm_repo: "{{ vars['platform'][app_runner_type][app_exe_obj]['helm']['repo'] }}"
    app_runner_helm_namespace: "{{ vars['platform'][app_runner_type][app_exe_obj]['helm']['namespace'] }}"
    app_runner_helm_name: "{{ vars['platform'][app_runner_type][app_exe_obj]['helm']['name'] }}"
  when: vars['platform'][app_runner_type][app_exe_obj]['runner']['command'] == 'helm'

- name: start container
  become: true
  docker_container:
    name: "klopac-{{ app_exe_obj }}"
    image: "kloiadocker/klopac-{{ vars['platform']['executor'][app_exe_obj]['runner']['name'] }}-runner:{{ vars['platform']['executor'][app_exe_obj]['runner']['version'] }}"
    command: "\"sleep infinity\""
    state: started
    tty: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

- name: change socket file mode
  delegate_to: "klopac-{{ int_exe_obj }}"
  shell: "sudo chmod 777 /var/run/docker.sock"

- name: add container to inventory
  add_host:
    name: "klopac-{{ app_exe_obj }}"
    ansible_host: "klopac-{{ app_exe_obj }}"
    ansible_user: root
    ansible_connection: docker
    groups: containers
  changed_when: false

- name: copy kubeconfig to runner
  delegate_to: "klopac-{{ app_exe_obj }}"
  copy:
    src: "/data/sensitive/{{ vars['platform']['name'] }}-{{ vars['platform']['environment'] }}.kubeconfig"
    dest: /tmp/kubeconfig
    mode: 400

- name: create app "{{ app_exe_obj }}"
  delegate_to: "klopac-{{ app_exe_obj }}"
  shell: "export KUBECONFIG=/tmp/kubeconfig; kubectl apply -f {{ app_helm_manifest_uri }}; helm upgrade -i --create-namespace --repo {{ app_runner_helm_repo }} -n {{ app_runner_helm_namespace }} --version {{ app_obj_version }} {{ app_runner_helm_name }} {{ app_runner_helm_name }}"
  register: app_create_log
  when: app_runner_helm_name is defined

- name: destroy container
  become: true
  docker_container:
    name: "klopac-{{ app_exe_obj }}"
    state: absent

- debug:
    msg: "{{ vars['app_create_log'] }}"
  when: vars['platform']['log']['level']=='debug'