---
- name: install "{{ item }}" helm chart
  include_tasks: ../roles/int/tasks/create_obj.yml
  with_items: "{{ int_obj }}"
  register: helm_create_log
  loop_control:
    loop_var: int_exe_obj
  when:
    - vars['int'][int_exe_obj]['runner']['type'] == 'executor'
    - vars['int'][int_exe_obj]['operation']['type'] == 'create'
    - vars['platform']['executor'][int_exe_obj]['helm'] is defined
    - vars['int'][int_exe_obj]['enabled'] == true

- debug:
    msg: "{{ helm_create_log }}"
  when: vars['platform']['log']['level']=='debug'