---
- name: "get runner type {{ int_exe_obj }}"
  set_fact:
    int_runner_type: "{{ vars['int'][int_exe_obj]['runner']['type'] }}"

- name: get runner name "{{ int_exe_obj }}"
  set_fact:
    int_runner_name: "{{ vars['platform'][int_runner_type][int_exe_obj]['runner']['name'] }}"

- name: get runner version "{{ int_exe_obj }}"
  set_fact:
    int_runner_version: "{{ vars['platform'][int_runner_type][int_exe_obj]['runner']['version'] }}"

- name: get "{{ int_exe_obj }}" version
  set_fact:
    int_obj_version: "{{ vars['platform'][int_runner_type][int_exe_obj]['version'] }}"

- name: get runner manifest "{{ int_exe_obj }}"
  set_fact:
    int_helm_manifest_uri: "{{ vars['platform'][int_runner_type][int_exe_obj]['manifest']['uri'] }}"

- name: get runner command for helm "{{ int_exe_obj }}"
  set_fact:
    int_runner_helm_repo: "{{ vars['platform'][int_runner_type][int_exe_obj]['helm']['repo'] }}"
    int_runner_helm_namespace: "{{ vars['platform'][int_runner_type][int_exe_obj]['helm']['namespace'] }}"
    int_runner_helm_name: "{{ vars['platform'][int_runner_type][int_exe_obj]['helm']['name'] }}"
  when: vars['platform'][int_runner_type][int_exe_obj]['runner']['command'] == 'helm'

- name: start container
  become: true
  docker_container:
    name: "klopac-{{ int_exe_obj }}"
    image: "kloiadocker/klopac-{{ vars['platform']['executor'][int_exe_obj]['runner']['name'] }}-runner:{{ vars['platform']['executor'][int_exe_obj]['runner']['version'] }}"
    command: "\"sleep infinity\""
    state: started
    tty: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

- name: change socket file mode
  delegate_to: "klopac-{{ int_exe_obj }}"
  shell: "sudo chmod 777 /var/run/docker.sock"

- name: add container to inventory
  add_host:
    name: "klopac-{{ int_exe_obj }}"
    ansible_host: "klopac-{{ int_exe_obj }}"
    ansible_user: root
    ansible_connection: docker
    groups: containers
  changed_when: false

- name: copy kubeconfig to runner
  delegate_to: "klopac-{{ int_exe_obj }}"
  copy:
    src: "/data/sensitive/{{ vars['platform']['name'] }}-{{ vars['platform']['environment'] }}.kubeconfig"
    dest: /tmp/kubeconfig
    mode: 400

- name: update int "{{ int_exe_obj }}"
  delegate_to: "klopac-{{ int_exe_obj }}"
  shell: "export KUBECONFIG=/tmp/kubeconfig; kubectl apply -f {{ int_helm_manifest_uri }}; helm upgrade -i --create-namespace --repo {{ int_runner_helm_repo }} -n {{ int_runner_helm_namespace }} --version {{ int_obj_version }} {{ int_runner_helm_name }} {{ int_runner_helm_name }}"
  register: int_update_log
  when: int_runner_helm_name is defined

- name: destroy container
  become: true
  docker_container:
    name: "klopac-{{ int_exe_obj }}"
    state: absent

- debug:
    msg: "{{ vars['int_update_log'] }}"
  when: vars['platform']['log']['level']=='debug'