---  
- hosts: localhost
  connection: local
  roles:
    - engine
  vars_files:
    - ../../vars/platform.yaml
    - ../../vars/image.yaml
    - ../../vars/instance.yaml
    - ../../vars/engine.yaml
