---  
- hosts: localhost
  connection: local
  roles:
    - engine
  vars_files:
    - /data/vars/platform.yaml
    - /data/vars/image.yaml
    - /data/vars/instance.yaml
    - /data/vars/engine.yaml
