---

COMPRESS_BUNDLE: true

# image_layer:
#   status: Healthy
#   id: 123456
#   provider: AWS

# instance_layer:
#   os:
#     name: 
#       value: ubuntu
#       match:
#     version: 20.04.4
#   utilization:
#     disk: "%20"
#     mem: "%30"
#     cpu: "%40"

# engine_layer:
#   version: v1.21.6
#   type: rke2

# gitops_layer:
#   type: argocd
#   status: true
#   apps:
#     - name: sock-shop-gitops
#       status: Healthy
#       endpoint: localhost:8082
#     - name: test-gitops
#       status: Unhealthy
#       endpoint: localhost:8083


# applications_layer:
#   - name: sock-shop
#     status: Healthy
#     endpoint: localhost:8080
#   - name: test
#     status: Unhealthy
#     endpoint: localhost:8081

# terraformFileCheck: false
# kubeconfigFileCheck: false