---

- name: "[INVENTORY-REFRESH] - Ensure 'servers & jump' section exists in inventory file"
  community.general.ini_file:
    path: ./inventory
    section: "{{ item }}"
    mode: '0666'
    allow_no_value: true
  with_items: 
  - servers
  - jump

- name: "[INVENTORY-REFRESH] - Update inventory file with Jump IP"
  ini_file:
    dest: "./inventory"
    section: "jump"
    option: "{{ platform.jump.ip }} ansible_ssh_private_key_file={{ ins.image.auth['pem.path'] }} ansible_user"
    values: "{{ ins.image.auth.user }}"
    no_extra_spaces: true
    mode: 0666
    state: present
    backup: false

- block:
  - name: "[INVENTORY-REFRESH] - Update inventory file with Master list"
    ini_file:
      dest: "./inventory"
      section: "servers"
      option: "{{ item }} ansible_ssh_private_key_file={{ ins.image.auth['pem.path'] }} ansible_user"
      values: "{{ ins.image.auth.user }}"
      no_extra_spaces: true
      mode: 0666
      state: present
      backup: false
    with_items: "{{ ins.master.net.ip.private.pool }}"

  - name: "[INVENTORY-REFRESH] - Update inventory file with Worker list"
    ini_file:
      dest: "./inventory"
      section: "servers"
      option: "{{ item }} ansible_ssh_private_key_file={{ ins.image.auth['pem.path'] }} ansible_user"
      values: "{{ ins.image.auth.user }}"
      no_extra_spaces: true
      mode: 0666
      state: present
      backup: false
    with_items: "{{ ins.worker.net.ip.private.pool }}"

  when: vars['ins']['image']['auth']['type'] == 'pem'

- block:
  - name: "[INVENTORY-REFRESH] - Update inventory file with Master list"
    ini_file:
      dest: "./inventory"
      section: "servers"
      option: "{{ item }} ansible_ssh_pass={{ ins.image.auth['password'] }} ansible_user"
      values: "{{ ins.image.auth.user }}"
      no_extra_spaces: true
      mode: 0666
      state: present
      backup: false
    with_items: "{{ ins.master.net.ip.private.pool }}"

  - name: "[INVENTORY-REFRESH] - Update inventory file with Worker list"
    ini_file:
      dest: "./inventory"
      section: "servers"
      option: "{{ item }} ansible_ssh_pass={{ ins.image.auth['password'] }} ansible_user"
      values: "{{ ins.image.auth.user }}"
      no_extra_spaces: true
      mode: 0666
      state: present
      backup: false
    with_items: "{{ ins.worker.net.ip.private.pool }}"

  when: vars['ins']['image']['auth']['type'] == 'password'


- name: "[INVENTORY-REFRESH] - Meta Refresh inventory"
  meta: refresh_inventory
