---
platform:
  executor:
    csiVsphere:
      version: v2.5.0
      runner:
        name: kubernetes
        version: v0.1
        command: helm
      helm:
        repo: 'https://kubernetes.github.io/cloud-provider-vsphere'
        namespace: kube-system
        name: vsphere-csi
