---
platform:
  executor:
    flux:
      1.24.3:
        runner:
          name: kubernetes
          version: v0.1
          command: helm
        manifest:
          uri: >-
            https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/crds.yaml
        helm:
          repo: 'https://charts.fluxcd.io'
          namespace: flux
          name: flux
