---
platform:
  executor:
    ingressNginx:
      version: 1.0.2
      runner:
        name: kubernetes
        version: v0.1
        command: helm
      helm:
        repo: 'https://kubernetes.github.io/ingress-nginx'
        namespace: ingress-nginx
        name: ingress-nginx
