---
platform:
  executor:
    k3s:
      type: shell
      tag: v1.23.5e+k3s1
      kubeconfig:
        path: "~/kubeconfig"
      dialect:
        command:
          pre: "curl -sLS https://get.k3sup.dev | sudo sh"
          create:  "k3sup install --ip $mgmt_ip --user $cluster_user --cluster --k3s-version $engine_version"
          master_join: "k3sup join --ip $item --user $cluster_user --server-user $cluster_user --server-ip $mgmt_ip --server --k3s-version $engine_version"
          worker_join: "k3sup join --ip $item --user $cluster_user --server-user $cluster_user --server-ip $mgmt_ip --k3s-version $engine_version"
      runner:
        name: klopac
        version: 5.2.0
      state:
        enabled: false
      healthcheck:
        type: kubeconfig
      outputs:
        kubeconfig:
          type: file
          path: kubecfg_path
