---
platform:
  executor:
    loggingPlg:
      version: v2.4.2
      runner:
        name: kubernetes
        version: v0.1
        command: helm
      helm:
        repo: 'https://grafana.github.io/helm-charts'
        namespace: logging
        name: loki-stack
        args:
          grafana:
            enabled: true
          prometheus:
            enabled: true
            pvc: disabled
          fluentBit:
            enabled: true
