---
platform:
  executor:
    rke2:
      type: shell
      tag: v1.24.9+rke2r1
      name: rke2
      kubeconfig:
        path: "/etc/rancher/rke2/rke2.yaml"
      kubectl:
        path: "/var/lib/rancher/rke2/bin/kubectl"
      dialect:
        command:
          work_on: instance
          pre: "wget -O rke2.sh https://get.rke2.io; sudo mkdir -p /etc/rancher/rke2 "
          master_join: "export INSTALL_RKE2_VERSION=$engine_version; sudo -E sh rke2.sh; sudo systemctl enable rke2-server; sudo systemctl start rke2-server"
          worker_join: "export INSTALL_RKE2_VERSION=$engine_version; export INSTALL_RKE2_TYPE=agent; sudo -E sh rke2.sh; sudo systemctl enable rke2-agent.service; sudo systemctl start rke2-agent.service"
          worker_clean: "sudo rke2-killall.sh; sudo rke2-uninstall.sh"
          master_clean: "sudo rke2-killall.sh; sudo rke2-uninstall.sh"
        file:
            destination: /etc/rancher/rke2/config.yaml
            content: |
              {% if mgmt_ip is defined %}
              server: https://{{ mgmt_ip }}:9345
              {% endif %}
              token: klopacdefaultSecret12345
              {% if mgmt_ip is not defined %}
              tls-san:
                - cluster.local
              {% endif %}
      runner:
        name: klopac
        version: 5.2.0
      state:
        enabled: false
      healthcheck:
        type: kubeconfig
      outputs:
        kubeconfig:
          type: file
          path: kubecfg_path
