platform:
  executor:
    vaultHashicorp:
      v1.9.4:
        runner: 
          name: kubernetes
          version: v0.1
          command: helm
        helm:
          repo: 'https://helm.releases.hashicorp.com'
          namespace: vault
          name: vault