---
app:
  enabled: true
  instana-agent:
    enabled: true
    operation:
      type: delete
    required:
      - enabled
      - name
      - operation.type
      - runner.type
    runner:
      type: executor
    type: agent
    inputs:
      agent.key: ''
      agent.downloadKey: ''
      agent.endpointHost: ''
      agent.endpointPort: ''
      cluster.name: ''
      zone.name: ''
  example:
    basedOn: gitops
    enabled: false
    namespace: example
    operation:
      type: create
      update:
        policy: apply
    required:
      - enabled
      - name
      - namespace
      - operation.type
      - runner.type
    runner:
      type: executor
  sock-shop:
    basedOn: gitops
    enabled: false
    namespace: sock-shop
    operation:
      type: create
      update:
        policy: apply
    required:
      - enabled
      - name
      - namespace
      - operation.type
      - runner.type
    runner:
      type: executor
  test:
    dependsOn: sock-shop
    enabled: false
    namespace: default
    operation:
      type: create
      update:
        policy: apply
    required:
      - enabled
      - name
      - namespace
      - operation.type
      - runner.type
    runner:
      type: executor
