---
# TODO: Extract clone and copy tasks as subtasks
- name: Clone repos with type "repo"
  ansible.builtin.git:
    repo: "{{ vars['platform']['repo'][item]['uri'] }}"
    dest: "/data/repo/{{ item }}"
    version: "{{ vars['platform']['repo'][item]['tag'] }}"
  with_items: "{{ vars['platform']['repo'].keys() | list }}"
- name: Copy states with type "repo"
  copy:
    src: "/data/bundle/{{ vars['platform']['repo'][item]['state']['file']['path'] }}"
    dest: "/data/repo/{{ item }}/"
    mode: u+rw,g-wx,o-rwx
  with_items:
    - "{{ vars['platform']['repo'].keys() | list }}"
  when: vars['platform']['repo'][item]['state']['enabled'] == true