---
- name: clean worker node configs
  shell: "export item={{ item }}; ssh $cluster_user@$item '{{ vars['platform']['executor'][engine_type]['dialect']['command']['worker_clean'] }}'"
  with_items:  "{{ vars['ins']['worker']['net']['ip']['private']['pool'] }}"
  environment:
    cluster_user: "{{ vars['img']['auth']['user'] }}"
  when: 
    - vars['platform']['executor'][engine_type]['type']=='shell'
    - vars['engine']['operation']['type']=='clean'

- name: clean worker node configs
  shell: "export item={{ item }}; ssh $cluster_user@$item '{{ vars['platform']['executor'][engine_type]['dialect']['command']['master_clean'] }}'"
  with_items:  "{{ vars['ins']['master']['net']['ip']['private']['pool'] }}"
  environment:
    cluster_user: "{{ vars['img']['auth']['user'] }}"
  when: 
    - vars['platform']['executor'][engine_type]['type']=='shell'
    - vars['engine']['operation']['type']=='clean'