---
- name: pre
  include: pre.yml
  when: engine.enabled == true

- name: create
  include: create.yml
  when: engine.enabled == true and engine.operation.type == 'create'

- name: update
  include: update.yml
  when: engine.enabled == true and engine.operation.type == 'update'

- name: clean
  include: clean.yml
  when: engine.enabled == true and engine.operation.type == 'clean'

- name: post
  include: post.yml
  when: engine.enabled == true