---
- name: "[ENGINE-SUBTASK] - Include Platform Variables"
  include_vars: 
    file: "{{ vars_path }}/platform.yaml"
    hash_behaviour: merge

- name: "[ENGINE-SUBTASK] - Include Default Engine Variables"
  include_vars: 
    file: "{{ vars_path }}/defaults/engine-{{ filename }}.yaml"
    hash_behaviour: merge

- name: "[ENGINE-SUBTASK] - Include Manifest File for Engine"
  include_vars: 
    file: "{{ manifests_path }}/{{ vars['engine']['runner']['type'] }}/{{ filename }}-{{ vars['engine'][filename]['version'] }}.yaml"
    hash_behaviour: merge

- name: "[ENGINE-SUBTASK] - Check that the kubeconfig exists"
  stat:
    path: "{{ sensitive_path }}/{{ vars['platform']['name'] }}-{{ vars['platform']['environment'] }}.kubeconfig"
  register: stat_result

# - name: "[ENGINE-SUBTASK] - Write kubeconfig file exists checks to outputs"
#   delegate_to: localhost
#   changed_when: false
#   shell: "echo 'kubeconfigFileCheck: false' >> {{ bundle_path }}/output.yaml"
#   when: not stat_result.stat.exists

- name: "[ENGINE-SUBTASK] - Copy Kubeconfig file with owner and permissions to the Bundle Directory"
  ansible.builtin.copy:
    src:  "{{ sensitive_path }}/{{ vars['platform']['name'] }}-{{ vars['platform']['environment'] }}.kubeconfig"
    dest: "{{ bundle_path }}/"
    owner: 1000
    group: 1000
    mode: '0644'
  when: stat_result.stat.exists
