---

# INVENTORY FILE - UPDATE
- hosts: localhost
  connection: local
  roles:
    - role: inventory

# INSTANCE TESTS
- hosts: servers
  gather_facts: false
  roles:
    - role: instance

# LAYER TESTS
- hosts: localhost
  connection: local
  roles:
    - role: image
    - role: engine
    - role: gitops
    - role: applications

# FINALIZE
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: finalize
