---

# INVENTORY FILE - UPDATE
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Include Image Variables
      include_vars: /data/vars/image.yaml
    - name: Include Platform Variables
      include_vars: /data/vars/platform.yaml
    - name: Include Instance Variables
      include_vars: /data/vars/instance.yaml
  tasks:
    - name: "[INVENTORY-REFRESH] - START"
      include_role:
        name: inventory
      when: vars['ins']['enabled'] == true

# INSTANCE TESTS
- hosts: jump
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Include Image Variables
      include_vars: /data/vars/image.yaml
    - name: Include Instance Variables
      include_vars: /data/vars/instance.yaml
  tasks:
    - name: "[INSTANCE-TESTS] - START"
      include_role:
        name: instance
      when: vars['ins']['enabled'] == true

# ENGINE TESTS & FINALIZE
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Include Engine Variables
      include_vars: /data/vars/engine.yaml
    - name: Include Instance Variables
      include_vars: /data/vars/instance.yaml
  tasks:
    - name: "[ENGINE-TESTS] - START"
      include_role:
        name: engine
      when: vars['engine']['enabled'] == true
    - name: "[FINALIZE] - START"
      include_role:
        name: finalize
      