---

# INVENTORY FILE - UPDATE
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Include Image Variables
      include_vars: "{{ vars_path }}/image.yaml"
    - name: Include Platform Variables
      include_vars: "{{ vars_path }}/platform.yaml"
    - name: Include Instance Variables
      include_vars: "{{ vars_path }}/instance.yaml"
  tasks:
    - name: "[INVENTORY-REFRESH] - START"
      include_role:
        name: inventory
      when: 
      - vars['ins']['enabled'] == true
      - vars['ins']['operation']['type'] != "delete"

# INSTANCE TESTS
- hosts: jump
  gather_facts: false
  pre_tasks:
    - name: Include Image Variables
      include_vars: "{{ vars_path }}/image.yaml"
    - name: Include Instance Variables
      include_vars: "{{ vars_path }}/instance.yaml"
  tasks:
    - name: "[INSTANCE-TESTS] - START"
      include_role:
        name: instance
      when: 
      - vars['ins']['enabled'] == true
      - vars['ins']['operation']['type'] != "delete"

# ENGINE TESTS & FINALIZE
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Include Engine Variables
      include_vars: "{{ vars_path }}/engine.yaml"
    - name: Include Instance Variables
      include_vars: "{{ vars_path }}/instance.yaml"
    - name: Include Platform Variables
      include_vars: "{{ vars_path }}/platform.yaml"
  tasks:
    - name: "[ENGINE-TESTS] - START"
      include_role:
        name: engine
      when:
      - vars['engine']['enabled'] == true
      - vars['engine']['operation']['type'] != "delete"
    - name: "[FINALIZE] - START"
      include_role:
        name: finalize
      
