---

- hosts: localhost
  tasks:
    - name: Create bundle from state and config files
      command: tar -czvf bundle.tar.gz ./data

    - name: Include variables from YAML
      include_vars: test_vars.yaml

    - name: Set facts
      set_fact:
        ec2: "{{ outputs['ec2'] }}"

    - name: "Remove inventory file if it exists"
      file:
        path: inventory
        state: absent

    - name: "Create inventory file"
      shell: echo "[servers]" > inventory

    - name: "Update inventory file with SERVER list"
      ini_file:
        dest: "./inventory"
        section: "servers"
        option: "{{ item.public_ip }} ansible_ssh_private_key_file={{ item.ssh_key }} ansible_ssh_user"
        values: "{{ item.remote_user }}"
        no_extra_spaces: yes
        mode: 0666
        state: present
        backup: no
      with_items: "{{ ec2 }}"

    - name: Refresh inventory
      meta: refresh_inventory

    - name: Write to file (for testing purposes)
      shell: echo "{{ outputs | to_nice_yaml(indent=2) }}" > output.yaml

- hosts: servers
  gather_facts: false
  tasks:
    - name: Include variables from YAML
      include_vars: test_vars.yaml

    - name: Get OS Name
      shell: |
        set -o pipefail
        cat /etc/os-release | grep -E "^NAME" | awk -F"=" '{ print $2 }' | sed 's/"//g'
      args:
        executable: /bin/bash
      register: os_name

    - name: Get OS Version
      shell: |
        set -o pipefail
        cat /etc/os-release | grep -E "^VERSION=" | awk -F"=" '{ print $2 }' | sed 's/"//g' | awk '{ print $1}'
      args:
        executable: /bin/bash
      register: os_version

    - name: Write os_name checks to outputs
      delegate_to: localhost
      shell: "echo 'os_name: {{ os_name.stdout | lower == img.os.name | lower }}' >> output.yaml"

    - name: Write os_version checks to outputs
      delegate_to: localhost
      shell: "echo 'os_version: {{ os_version.stdout | lower == img.os.version | lower }}' >> output.yaml"
