---

# INVENTORY FILE - UPDATE
- hosts: localhost
  connection: local
  tasks:
  - name: Include Image Variables
    include_vars: /data/vars/instance.yaml
  - name: Include inventory role 
    include_role:
      name: inventory
    when: vars['ins']['enabled'] == true

# INSTANCE TESTS
- hosts: servers
  gather_facts: false
  tasks:
  - name: Include Image Variables
    include_vars: /data/vars/instance.yaml
  - name: Include instance role 
    include_role:
      name: instance
    when: vars['ins']['enabled'] == true

# # LAYER TESTS
# - hosts: localhost
#   connection: local
#   roles:
#     - role: engine
#     - role: gitops
#     - role: applications

# FINALIZE
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: finalize
