---

- name: Include variables
  include_vars: 
    file: "/data/vars/defaults/ins-{{ filename }}.yaml"
    hash_behaviour: merge

- name: Include Manifest
  include_vars: 
    file: "/data/manifests/{{ vars['ins']['runner']['type'] }}/{{ filename }}-{{ vars['ins'][filename]['version'] }}.yaml"

- name: Check that the terraform.tfstate exists
  stat:
    path: "/data/repo/{{ filename }}/{{ vars['platform']['repo'][filename]['outputs']['file']['path'] }}"
  register: stat_result

- name: Write terraform state file exists checks to outputs
  delegate_to: localhost
  changed_when: false
  shell: "echo 'terraformFileCheck: false' >> /data/bundle/output.yaml"
  when: not stat_result.stat.exists

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "/data/repo/{{ filename }}/{{ vars['platform']['repo'][filename]['outputs']['file']['path'] }}"
    dest: /data/bundle/terraform.tfstate
    owner: 1000
    group: 1000
    mode: '0644'
  when: stat_result.stat.exists