---

# Include layer variables
- name: "[VALIDATOR - REQUIRED FIELD VALIDATION] Include image vars"
  include_vars: /data/vars/image.yaml

- name: "[VALIDATOR - REQUIRED FIELD VALIDATION] Include engine vars"
  include_vars: /data/vars/engine.yaml

- name: "[VALIDATOR - REQUIRED FIELD VALIDATION] Include engine vars"
  include_vars: /data/vars/instance.yaml

- name: "[VALIDATOR - REQUIRED FIELD VALIDATION] Include engine vars"
  include_vars: /data/vars/platform.yaml

- name: "[VALIDATOR - REQUIRED FIELD VALIDATION] Include engine vars"
  include_vars: /data/vars/gitops.yaml

- name: "[VALIDATOR - REQUIRED FIELD VALIDATION] Include engine vars"
  include_vars: /data/vars/integrations.yaml

# Make nested check for required fields of each layer
- include: nested_check_loop.yml
  vars:
    obj: "{{ item.dict }}"
    layerName: "{{ item.name }}"
  with_items:
    - name: "Image"
      dict: "{{ img }}"
    - name: "Engine"
      dict: "{{ engine }}"
    - name: "Instance"
      dict: "{{ ins }}"
    - name: "Platform"
      dict: "{{ platform }}"
    - name: "Gitops"
      dict: "{{ gitops }}"
    - name: "Integrations"
      dict: "{{ int }}"
