---
- name: Include Engine File
  include_vars: /data/vars/engine.yaml
- name: Include Instance File
  include_vars: /data/vars/instance.yaml
- name: Include Image File
  include_vars: /data/vars/image.yaml
- name: Include Platform File
  include_vars: /data/vars/platform.yaml

- name: Include Engine Defaults File
  include_vars: 
    file: /data/vars/defaults/engine-{{ engine.type }}.yaml
    hash_behaviour: merge
- name: Include Image Defaults File
  include_vars: 
    file: /data/vars/defaults/img-{{ img.type }}.yaml
    hash_behaviour: merge
- name: Inclue Instance Defaults File
  include_vars: 
    file: /data/vars/defaults/ins-{{ ins.type }}.yaml
    hash_behaviour: merge

- name: Include Engine Manifest File
  include_vars: 
    file: /data/manifests/{{ engine.runner.type }}/{{ engine.type }}-{{ engine[engine.type]["version"] }}.yaml
    hash_behaviour: merge
- name: Include Image Manifest File
  include_vars: 
    file: /data/manifests/{{ img.runner.type }}/{{ img.type }}-{{ img[img.type]["version"] }}.yaml
    hash_behaviour: merge
- name: Include Instance Manifest File
  include_vars: 
    file: /data/manifests/{{ ins.runner.type }}/{{ ins.type }}-{{ ins[ins.type]["version"] }}.yaml
    hash_behaviour: merge
