runner:
  cloud:
    version: v0.1
    awscli:
      version: 2.4.23
      inputs:
        aws_access_key_id: "{{ aws.aws_access_key_id }}"
        aws_secret_access_key: "{{ aws.aws_secret_access_key }}"
    azurecli:
      version: 2.34.1
      inputs:
        username: "{{ azure.username }}"
        password: "{{ azure.password }}"
    gcloud:
      version: 375.0.0
      inputs:
        username: "{{ gcloud.username }}"
        password: "{{ gcloud.password }}"