---
platform:
  runner:
    terraform-aws:
      v0.1:
        terraform:
          version: v1.1.7
          inputs:
            path: /app
            log:
              level: '{{ general.log.level }}'
        awscli:
          version: 2.4.23
          inputs:
            aws_access_key_id: '{{ aws.aws_access_key_id }}'
            aws_secret_access_key: '{{ aws.aws_secret_access_key }}'
