---
- name: Provisioner Playbook
  hosts: localhost
  tasks:
  - name: include_engine_file
    include_vars: /data/vars/engine.yaml
  - name: include_instance_file
    include_vars: /data/vars/instance.yaml
  - name: include_image_file
    include_vars: /data/vars/image.yaml
  - name: include_engine_defaults_file
    include_vars: 
      file: /data/vars/defaults/engine-{{ engine.type }}.yaml
      hash_behaviour: merge
  - name: include_image_defaults_file
    include_vars: 
      file: /data/vars/defaults/img-{{ img.type }}.yaml
      hash_behaviour: merge
  - name: include_instance_defaults_file
    include_vars: 
      file: /data/vars/defaults/ins-{{ ins.type }}.yaml
      hash_behaviour: merge
  - name: include_engine_manifest_file
    include_vars: 
      file: /data/manifests/{{ engine.runner.type }}/{{ engine.type }}-{{ engine[engine.type]["version"] }}.yaml
  - name: include_img_manifest_file
    include_vars: 
      file: /data/manifests/{{ img.runner.type }}/{{ img.type }}-{{ img[img.type]["version"] }}.yaml
      hash_behaviour: merge
  - name: include_ins_manifest_file
    include_vars: 
      file: /data/manifests/{{ ins.runner.type }}/{{ ins.type }}-{{ ins[ins.type]["version"] }}.yaml
      hash_behaviour: merge
  # TODO: Extract clone and copy tasks as subtasks
  - name: clone
    ansible.builtin.git:
      repo: "{{ vars['platform']['repo'][item]['uri'] }}"
      dest: "/data/repos/{{ item }}"
      version: "{{ vars['platform']['repo'][item]['tag'] }}"
    with_items: "{{ vars['platform']['repo'].keys() | list }}"
  - name: clone
    ansible.builtin.git:
      repo: "{{ vars['platform']['executor'][item]['uri'] }}"
      dest: "/data/repos/{{ item }}"
      version: "{{ vars['platform']['executor'][item]['tag'] }}"
    with_items: "{{ vars['platform']['executor'].keys() | list }}"
  - name: copy
    copy:
      src: "/data/bundle/{{ vars['platform']['repo'][item]['state']['file']['path'] }}"
      dest: "/data/repos/{{ item }}/"
      mode: u+rw,g-wx,o-rwx
    with_items:
      - "{{ vars['platform']['repo'].keys() | list }}"
    when: vars['platform']['repo'][item]['state']['enabled'] == true
  - name: copy
    copy:
      src: "/data/bundle/{{ vars['platform']['executor'][item]['state']['file']['path'] }}"
      dest: "/data/repos/{{ item }}/"
      mode: u+rw,g-wx,o-rwx
    with_items:
      - "{{ vars['platform']['executor'].keys() | list }}"
    when: vars['platform']['executor'][item]['state']['enabled'] == true