---
- name: Provisioner Playbook
  hosts: localhost
  tasks:
  - name: include_engine_file
    include_vars: ../vars/engine.yaml
  - name: include_manifest_file
    include_vars: ../manifests/repo/{{ engine.type }}.yaml
  - name: clone
    ansible.builtin.git:
      repo: "{{ repo.uri }}"
      dest: "/data/repos/{{ repo.name }}"
      version: "{{ repo.branch }}"
  - name: copy
    copy:
      src: "{{ item.path }}"
      dest: "/data/repos/{{ repo.name }}/"
      mode: u+rw,g-wx,o-rwx
    with_items: "{{ repo.outputs.values() | list }}"
    when: item.type == 'file'
