platform:
  repo:
    kubeadm:
      v1.23.4:
        uri: ''
        type: git
        branch: master
        tag: v1.23.4
        runner:
          name: ansible
          version: 5.2.0
        state:
          enabled: false
        healthcheck:
          type: kubeconfig
        outputs:
          kubeconfig:
            type: file
            path: kubecfg_path