platform:
  repo:
    packer:
      v1.8.0:
        uri: ''
        type: git
        branch: master
        tag: v1.8.0
        runner:
          name: packer
          version: 1.8.0
        state:
          enabled: false
        healthcheck:
          type: kubeconfig
        outputs:
          kubeconfig:
            type: file
            path: kubecfg_path
        