repo:
  rke-ansible:
    name: "RKE-Ansible"
    uri: "https://github.com/kloia/rke-ansible"
    type: git
    branch: master
    runner:
      name: ansible
      version: 5.2.0
    state:
      enabled: false
    healthcheck:
      type: kubeconfig
    inputs:
      servers: ''
      pemfile: ''
    outputs:
      kubeconfig:
        type: file
        path: kubecfg_path
  