repo:
  rke2:
    name: "RKE2-Ansible"
    uri: "https://github.com/kloia/rke2-ansible"
    type: git
    branch: main
    runner:
      name: ansible
      version: 5.2.0
    state:
      enabled: false
    healthcheck:
      type: kubeconfig
    inputs:
      servers: ''
      agents: ''
      pemfile: ''
    outputs:
      kubeconfig:
        type: file
        path: kubecfg_path
  