---
platform:
  repo:
    rke2:
      main:
        uri: 'https://github.com/kloia/rke2-ansible'
        type: git
        branch: main
        runner:
          name: ansible
          version: 5.2.0
        state:
          enabled: false
        healthcheck:
          type: kubeconfig
        outputs:
          kubeconfig:
            type: file
            path: kubecfg_path
