name: Go

on:
  push:
    branches: [ 0.1-alpha ]
  pull_request:
    branches: [ 0.1-alpha ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: cd entrypoint && go build cmd/main.go

      - name: Test
        run: cd entrypoint && go test -v ./...

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: "${{ secrets.DOCKER_HUB }}/klopac-runner-ci"
          tag: 0.1
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          dockerfile: Docker/runner/klopac/Dockerfile
