name: Kubernetes Runner Image Build and Publish

on:
  push:
    branches: [ 0.1-alpha ]
    paths:
      - 'docker/runner/kubernetes/Dockerfile'
      
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: "${{ secrets.DOCKER_HUB }}/klopac-kubernetes-runner"
          tag: 0.1
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          dockerfile: Docker/runner/kubernetes/Dockerfile
  test:
    runs-on: ubuntu-20.04
    needs: build
    container: 
      image: "docker.io/kloiadocker/klopac-kubernetes-runner:0.1"
      credentials:
        username: ${{ secrets.DOCKER_HUB }}
        password: ${{ secrets.DOCKER_HUB_KEY }}
    steps:
      - run: kubectl version --client
        name: Check kubectl version
      - run: helm version
        name: Check helm version
      - run: kustomize version
        name: Check kustomize version